### ISSUE TITLE
Return data as ints

### ISSUE THREAD

**Issue by Rondom** [c0ding/hazelnut#1]
It would be nice to consume the data as integers in order to be able to do one's own formatting such as converting to MB or GB, rounding etc. without having to resort to string manipulation which, I suppose, is one of the goals of this library.

**Comment by barnumbirr** [comment]
Hi there,

so what would you like to have? Would indeed be great to have a method call, I you give me a concrete example of how you'd want to have it, I'll implement it ASAP.

Cheers.

**Comment by eugene-eeo** [comment]
I think @Rondom means something like:

``` python
>>> mem.get('inactive')
671312
```

**Comment by barnumbirr** [comment]
Oh right, I see. If I find some time, I'll implement it this weekend.

**Comment by barnumbirr** [comment]
Hi there again,

I've had a quick stab at this and [have gotten this far for now](https://github.com/c0ding/hazelnut/blob/development/hazelnut/core.py). It's still pretty rough and needs some tuning but it works.
@Rondom @eugene-eeo is that how you guys imagined it?

Cheers.

**Comment by eugene-eeo** [comment]
👍

**Comment by barnumbirr** [comment]
Hi,

so basically the last thing I'm still struggling with is case sensitivity. This work just fine

``` python
>>> mem.get('Inactive')
40640
```

but this won't work:

``` python
>>> mem.get('inactive')
None
```

Will have to figure out a proper way of handling this.

**Comment by eugene-eeo** [comment]
Compile regexes using `re.IGNORECASE`?

**Comment by barnumbirr** [comment]
That's what I thought I'd use in the first place. But here's the problem:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

mem = ['MemTotal:        8092252 kB', 'MemFree:         6874624 kB', 'MemAvailable:    7215760 kB', 'Buffers:          220144 kB', 'Cached:           248328 kB', 'SwapCached:            0 kB', 'Active:          1016256 kB', 'Inactive:          40640 kB', 'Active(anon):     589128 kB', 'Inactive(anon):      940 kB', 'Active(file):     427128 kB', 'Inactive(file):    39700 kB', 'Unevictable:           0 kB', 'Mlocked:               0 kB', 'SwapTotal:      16776188 kB', 'SwapFree:       16776188 kB', 'Dirty:                 0 kB', 'Writeback:             0 kB', 'AnonPages:        588424 kB', 'Mapped:            87848 kB', 'Shmem:              1644 kB', 'Slab:             109508 kB', 'SReclaimable:      86504 kB', 'SUnreclaim:        23004 kB', 'KernelStack:        3568 kB', 'PageTables:         6676 kB', 'NFS_Unstable:          0 kB', 'Bounce:                0 kB', 'WritebackTmp:          0 kB', 'CommitLimit:    20822312 kB', 'Committed_AS:    1624976 kB', 'VmallocTotal:   34359738367 kB', 'VmallocUsed:      356984 kB', 'VmallocChunk:   34359367624 kB', 'HardwareCorrupted:     0 kB', 'AnonHugePages:         0 kB', 'HugePages_Total:       0', 'HugePages_Free:        0', 'HugePages_Rsvd:        0', 'HugePages_Surp:        0', 'Hugepagesize:       2048 kB', 'DirectMap4k:       63164 kB', 'DirectMap2M:     8222720 kB']

x = re.compile('inactive', re.IGNORECASE)
sub_list = filter(x.match, mem)
print sub_list

['Inactive:          40640 kB', 'Inactive(anon):      940 kB', 'Inactive(file):    39700 kB']

```

This works and I could definitely use the result. But when you try and use

``` python
x = re.compile('inactive(anon)', re.IGNORECASE)
```

It simply returns `[]`.
Guess case insensitivity is not an option here.

**Comment by eugene-eeo** [comment]
You can check if the regex matched the entire string by checking for the indexes returned by the `group()` method of a match object.

**Comment by Rondom** [comment]
Why would one want case-insensitivity?

**Comment by barnumbirr** [comment]
added in https://github.com/c0ding/hazelnut/commit/408f5ab3e789ff29b1f9969988608db11bd99c11
