### ISSUE TITLE
Can't Install from Pip

### ISSUE THREAD

**Issue by dagrooms52** [c0ding/hazelnut#7]
I like the project, I'm trying to use it in a Docker container to read Docker host memory usage. I'm having trouble installing from pip though.

I ran `pip install hazelnut` on a Raspberry Pi 3 and got the following trace:

```
root@4cc7b8d15e61:/host/proc# pip install hazelnut
Collecting hazelnut
  Downloading hazelnut-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9s508nox/hazelnut/setup.py", line 16, in <module>
        long_description=file('README.md','r').read(),
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9s508nox/hazelnut/
```

**Comment by barnumbirr** [comment]
Hey,

what version of ```python``` / ```pip``` are you using?

Cheers.

**Comment by dagrooms52** [comment]
Python 3.6.2
Pip 9.0.1

**Comment by barnumbirr** [comment]
Looks like I never updated the library to work with ```Python 3```. I'll look into it this weekend and will push a new version to PyPi once I'm done.

**Comment by barnumbirr** [comment]
@dagrooms52 I've just pushed ```v.4.1.1``` to ```PyPi```. Can you give it a spin and let me know how it works?

Cheers.

**Comment by dagrooms52** [comment]
Nice! All looks good, was able to install from pip and run the `MemInfo` sample. Thanks a lot!
